name: Publish

on:
  workflow_dispatch:
  push:
    branches: ['feature-**', 'fix-**', staging, master]
  schedule:
    # At 02:30 on Saturday
    - cron: '30 2 * * 6'

jobs:
  publish-unmanic-central-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      # ---
      - name: Set Docker image name
        id: set-image
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "docker_hub_image:josh5/unmanic-central-datastore"
          echo "docker_hub_image=josh5/unmanic-central-datastore" >> $GITHUB_OUTPUT
          echo "ghcr_image:ghcr.io/${ORG:?}/unmanic-central-datastore"
          echo "ghcr_image=ghcr.io/${ORG:?}/unmanic-central-datastore" >> $GITHUB_OUTPUT

      # ---
      - name: Log into GHCR registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---
      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ steps.set-image.outputs.docker_hub_image }}:latest

      # ---
      - name: Tag and push to GHCR
        run: |
          echo "Tagging ${{ steps.set-image.outputs.docker_hub_image }}:latest as ${{ steps.set-image.outputs.ghcr_image }}:latest"
          docker tag ${{ steps.set-image.outputs.docker_hub_image }}:latest ${{ steps.set-image.outputs.ghcr_image }}:latest
          docker push ${{ steps.set-image.outputs.ghcr_image }}:latest

  publish-compose-templates:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [publish-unmanic-central-image]
    permissions:
      contents: write
    steps:
      # ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---
      - name: Publish Templates
        uses: Josh5/action.publish-swarm-stack@841e62adec930611e3c27924982eb85979a42f9c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          templates_path: compose-templates
          branch_name: release/latest
